#!/bin/bash

#########################
#      installation     #
#########################

# Update
sudo pacman -Syu --noconfirm

# packages
sudo pacman -S --noconfirm --needed yay 

yay -S --noconfirm --needed cava ttf-poppins firefox i3-gaps i3blocks i3lock i3status fortune-mod sl flameshot feh vlc neofetch rofi picom lxappearance-gtk3 which kitty tmux curl gedit zsh htop python-pip nodejs yarn ranger texmaker zip unzip tar unrar p7zip deepin-icon-theme deepin-gtk-theme elementary-icon-theme ttf-font-awesome otf-font-awesome ttf-hack  dunst cava ttf-poppins

# neovim-plugin
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

#.oh-my-zsh
cd $HOME/.oh-my-zsh/plugins/
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git

#fzf installation
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
