#!/bin/bash

#########################
#      installation     #
#########################

# Update
sudo pacman -Syu --noconfirm

# packages
sudo pacman -S --noconfirm --needed firefox i3-gaps i3blocks i3lock i3status fortune-mod sl flameshot feh neofetch rofi picom lxappearance-gtk3 which kitty tmux curl gedit zsh htop python-pip nodejs yarn ranger texmaker zip unzip tar unrar p7zip deepin-icon-theme deepin-gtk-theme elementary-icon-theme ttf-font-awesome otf-font-awesome ttf-hack  dunst
# yay
sudo pacman -S --noconfirm --needed git base-devel
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si --noconfirm --needed

yay -S --noconfirm --needed cava ttf-poppins

# neovim-plugin
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'



#unzip $HOME/zivoel_manjaro/dotfiles/oh-my-zsh/oh-my-zsh.zip
#cp -a -f -r $HOME/zivoel_manjaro/dotfiles/oh-my-zsh/.*   $HOME/
#cp -a -f -r $HOME/zivoel_manjaro/dotfiles/*   $HOME/.config/

# configurating some scripts
#chmod +x $HOME/.config/i3/blocks/*
#chmod +x $HOME/.config/rofi/scripts/*
#chmod +x $HOME/.config/my_scripts/*.sh


#.oh-my-zsh
cd $HOME/.oh-my-zsh/plugins/
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git

#fzf installation
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
